### ISSUE TITLE
Misunderstanding

### ISSUE THREAD

**Issue by 1999** [floatdrop/gulp-bem#16]
1. https://github.com/floatdrop/gulp-bem#bemlevels-options link to deps function is broken (leads to 404)
2. API question.

```javascript
var levels = [
        'bower_components/bem-core/common.blocks',
        'bower_components/bem-core/desktop.blocks',
        'ymodules',
        'blocks/common'
    ];

    var bem = require('gulp-bem');
    var concat = require('gulp-concat');

    var tree = bem(levels);

    tree.deps('app/pages/common')
        .pipe(bem.src('*.scss'))
        .pipe(concat('sample.scss'))
        .pipe(gulp.dest('./'));
```

FOA whys is this code not outputting anything? sample.scss has not been created and no error is displayed. Then, what is `deps` function used for? Is this something like a path to bemdecl/bemjson file with all blocks used inside web page? Can I just set asterisk to say "I want all blocks from levels"?

**Comment by floatdrop** [comment]
I don't think we tested `gulp-bem` against `bem-core`. May be something wrong with `deps` resolution.

**Comment by 1999** [comment]
What have you tested it against then? And what about my second question?

> Then, what is deps function used for? Is this something like a path to bemdecl/bemjson file with all blocks used inside web page? Can I just set asterisk to say "I want all blocks from levels"?

**Comment by floatdrop** [comment]
> [deps function](https://github.com/floatdrop/deps-graph#depsgraphdepsbem) - Gets all dependencies for block. Returns dependencies in order, that defined by require and expect of corresponding BEM objects and levels of declaration.

We tested it on `getbem` site, when it was built with deps. Now we migrated on `webpack` and recommend you to do the same.

I don't think `gulp-bem` will be developed further.

**Comment by 1999** [comment]
That's quiet hard for us right now :)
Anyway thank you!

**Comment by floatdrop** [comment]
@1999 I heard, that they released self-contained JS and CSS files with all styles and code, so you can try use them and any build system you want ;)

**Comment by 1999** [comment]
I'm not talking about bem-components this time. Мы не используем Лего.
